name: First Workflow

on:
  push:
    branches:
        - "main"
        - "develop"
        - "realse"
  jobs:
    lab-job:
        run-ons: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps' 
